parameters:
#    landing_pages_todosganan_site_subscribe.example.class: Landing\Pages\Todosganan\Site\SubscribeBundle\Example

services:
#    landing_pages_todosganan_site_subscribe.example:
#        class: %landing_pages_todosganan_site_subscribe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
